### PR TITLE
Test High-Res MIP

### PR DESCRIPTION
**Pull request by jbusecke**
#72

### CODE REVIEW

**Comment by jbusecke** [comment]
Oh yes. I activated the 'full' dynamic chunking for the first time, and look at this beautiful test dataset @rsignell:

image

I am quite happy with this hehe.

**Comment by jbusecke** [comment]
Trying the other datasets now as PR versions (which only loads two timesteps), will then move the iids to the main iid list and merge. Onwards!

**Comment by rsignell** [comment]
Is the final dataset going to be chunked 1 in time though?

**Comment by jbusecke** [comment]
No this is a downside of the pruning we do here...the dynamic chunking function only sees 2 files, and thus the final chunking will be different on the final product...

**Comment by rsignell** [comment]
@jbusecke where do we stand on this Hi-Res mip dataset?   
Did the non-pruned version get made available somewhere?

**Comment by jbusecke** [comment]
We were running into a pretty gnarly error that (in my intuition is caused by very large datasets with 'orthogonal' rechunking (going from time only to 'chunked all over the place') - read exactly these HighResMIP datasets). I am currently pushing hard on getting [an MRE](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/715) for this and hopefully that can serve as fuel to fix that bug upstream. Sorry for the delay again...

**Comment by rsignell** [comment]
Thanks for keeping this alive, @jbusecke !

**Pull request merged**
