### PR TITLE
Use action v0.2 release

### PR DESCRIPTION
**Pull request by cisaacstern**
I believe everything has been fixed such that the new action release can support the use case here. Let's see!

### CODE REVIEW

**Comment by cisaacstern** [comment]
Looks like we need `git` in the container to install git dependencies with pip... I'll fix that now.

**Comment by cisaacstern** [comment]
The prior failure should be fixed by https://github.com/pangeo-forge/deploy-recipe-action/pull/24, so just installing from there first, to confirm functionality, before releasing action again.

**Comment by cisaacstern** [comment]
@jbusecke this LGTM, but tagging for your review in case I've missed something.

**Comment by jbusecke** [comment]
Phenomenal work @cisaacstern. 

I just checked and at least the last submitted recipe (https://console.cloud.google.com/dataflow/jobs/us-central1/2023-11-21_13_40_16-747618565999184631;graphView=0?project=leap-pangeo&walkthrough_id=dataflow_index&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22)) did succeed in dataflow. I will merge this now!

**Pull request merged**
