### PR TITLE
Baseline test for deploy-action and CMIP6 recipe

### PR DESCRIPTION
**Pull request by jbusecke**
This is an attempt to systematically debug the CMIP6 recipe deployment on dataflow with the latest deploy action. 
I have hardcoded the urls/iids to establish a baseline. I want one dataset to go through without any of the new stuff I have developed:
- Dynamic chunking (EDIT: This now very much includes the dynamic chunking)
- Url parsing/reading to/from BigQuery

I ran into a TON of trouble trying to develop this locally, which I still think is an important option that people should have (more to be discussed).

cc @cisaacstern

### CODE REVIEW

**Comment by jbusecke** [comment]
@cisaacstern I took pangeo-forge-esgf entirely out of the picture, but now I am running into a different issue:
```
"/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/internal/cloudpickle_pickler.py", line 95, in loads unpickled = cloudpickle.loads(s) ModuleNotFoundError: No module named 'pangeo_forge_recipes.types'
```
Is this the same issue of a wrong pgf-recipes version?

**Comment by jbusecke** [comment]
My local laptop run failed with a server disconnect, possibly due to my terrible internet connection 😁. I should probably try to run this on the LEAP hub with an specified environment file?

**Comment by jbusecke** [comment]
Tried to add `#egg=pangeo_forge_recipes` to the `requirements.txt`

**Comment by cisaacstern** [comment]
🍿

**Comment by jbusecke** [comment]
Oh wow. That seems to have worked...

**Comment by cisaacstern** [comment]
🚀

**Comment by jbusecke** [comment]
Still taking quite a long time though: 

image

But that might be due to the small chunks? Lets see if it actually finishes.

**Comment by jbusecke** [comment]
One note for later: I think we can scale the instance size back on this
image

**Comment by jbusecke** [comment]
Yay, it ran successfully!
image
- The chunksize seems indeed responsible for the long runtime
- Seems like every dependency needs the `#egg...` thing, which I honestly do not understand. But adding pangeo-forge-esgf without the addition did produce the same failures again!
- Increasing the chunksize seems to have reduced the memory useage? Does this make sense at all? image

**Comment by cisaacstern** [comment]
> Yay, it ran successfully!

🎉 

> The chunksize seems indeed responsible for the long runtime

Sweet, glad it was something simple.

> Seems like every dependency needs the #egg... thing, which I honestly do not understand. But adding pangeo-forge-esgf without the addition did produce the same failures again!

Under certain conditions (pip version, packaging style, etc.?) this is necessary for pip to know how to install a git repo under the correct package name. I don't understand the specifics more than that. 😄 

> Increasing the chunksize seems to have reduced the memory useage? Does this make sense at all? 

Potentially makes sense. Larger chunks means that to assemble each chunk more data needs to be held in memory. Bumping from `{'time': 10}` to `{'time': 1000}` could have been enough a bump to be noticeable.

**Comment by cisaacstern** [comment]
The error on deploy from the latest commit:

```
TypeError: 'AsSingleton' object is not subscriptable", "status": "failed"***
```
should be reproducible with pangeo-forge-runner + LocalDirectBakery.

**Comment by cisaacstern** [comment]
@jbusecke you should be able to re-trigger by just removing and then re-applying the label. No need to add a placeholder commit. This is one of the great things about label-based deployment!

**Comment by jbusecke** [comment]
Unfortunately, the local testing totally fails for me currently (do to my internet I suppose). I think this reinforces the need for me to be able to run this maybe on the LEAP hub.

**Comment by cisaacstern** [comment]
> I think this reinforces the need for me to be able to run this maybe on the LEAP hub.

Is there some barrier to doing that, should be simple, no?

**Comment by jbusecke** [comment]
> Is there some barrier to doing that, should be simple, no?

I suspect some env nonsense, but maybe that is just my 2am brain keeping me from engaging in anything conda haha.

**Comment by jbusecke** [comment]
Just got
```
File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/dynamic_target_chunks.py", line 80, in dynamic_target_chunks_from_schema raise ValueError( ValueError: target_chunks_aspect_ratio must contain all dimensions in dataset. Got dict_keys(['lon', 'lat', 'time']) but expected ['time', 'lat', 'lon', 'bnds'] [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|KeepOnlyVariableId|StoreToZarr/StoreToZarr/Map(determine_target_chunks)-ptransform-42']
```
Strong argument for modifying the dynamic chunking to not require all dimensions as input. See also [ comment here](https://github.com/leap-stc/cmip6-leap-feedstock/blob/5e305d88e421d549ab73614f2ca8d416b32be06f/feedstock/recipe.py#L192). 

For tonight will provide inputs for `bnds`.

**Comment by jbusecke** [comment]
Ok now I got something more interesting:
```
File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/transforms/core.py", line 1956, in <lambda>
    wrapper = lambda x: [fn(*x)]
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/rechunking.py", line 214, in combine_fragments
    raise ValueError("Cannot combine fragments because they do not form a regular hypercube.")
ValueError: Cannot combine fragments because they do not form a regular hypercube. [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|KeepOnlyVariableId|StoreToZarr/StoreToZarr/Rechunk/MapTuple(combine_fragments)-ptransform-31']
"
```
Ill try one more run an additional print statement I implemented over at https://github.com/pangeo-forge/pangeo-forge-recipes/pull/546, and then call it a night.

**Comment by jbusecke** [comment]
Hmm this
```
"apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/transforms/core.py", line 1877, in <lambda> wrapper = lambda x, *args, **kwargs: [fn(x, *args, **kwargs)] File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/writers.py", line 91, in store_dataset_fragment _store_data(vname, da.variable, index, zgroup) File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/writers.py", line 48, in _store_data raise ValueError( ValueError: Region (slice(1, 2, None), slice(7090, 10635, None), slice(80, 160, None), slice(0, 160, None)) does not align with Zarr chunks (3545, 80, 160). [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|KeepOnlyVariableId|StoreToZarr/StoreToZarr/StoreDatasetFragments/Map(store_dataset_fragment)-ptransform-32']
```

reminds me of https://github.com/pangeo-forge/pangeo-forge-recipes/issues/504. 

As far as I can tell the dynamic chunking infers target_chunks as `{'time':3545, 'lat':80, 'lon':160, 'bnds':1}`, where the `bnds` part is the issue? 

**next steps to try**
- [ ] Does [`decode_coords=all`](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/504#issuecomment-1485235403) help? (I would not assume that since the custom preprocessor here should be stricter)
- [ ] Do we recover the failure if we provide the above values statically?
- [ ] Does setting `'bnds':-1` help at all?

**Comment by cisaacstern** [comment]
Great progress @jbusecke, as always lmk if/how I can help.

**Comment by jbusecke** [comment]
Just confirmed that passing the chunks statically also produces a similar error: 
<details>
Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/rechunking.py", line 211, in combine_fragments starts = _invert_meshgrid(*starts_cube[::-1])[::-1] File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/rechunking.py", line 142, in _invert_meshgrid assert all( AssertionError During handling of the above exception, another exception occurred: Traceback (most recent call last): File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/transforms/core.py", line 1956, in <lambda> wrapper = lambda x: [fn(*x)] File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/rechunking.py", line 214, in combine_fragments raise ValueError("Cannot combine fragments because they do not form a regular hypercube.") ValueError: Cannot combine fragments because they do not form a regular hypercube. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute response = task() File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda> lambda: self.create_worker().do_instruction(request), request) File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 597, in do_instruction return getattr(self, request_type)( File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle bundle_processor.process_bundle(instruction_id)) File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle input_op_by_transform_id[element.transform_id].process_encoded( File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 227, in process_encoded self.output(decoded_value) File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 1507, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process File "/srv/conda/envs/notebook/lib/python3.9/site-packages/apache_beam/transforms/core.py", line 1956, in <lambda> wrapper = lambda x: [fn(*x)] File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pangeo_forge_recipes/rechunking.py", line 214, in combine_fragments raise ValueError("Cannot combine fragments because they do not form a regular hypercube.") ValueError: Cannot combine fragments because they do not form a regular hypercube. [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|KeepOnlyVariableId|StoreToZarr/StoreToZarr/Rechunk/MapTuple(combine_fragments)-ptransform-31']
</details>

I am not seeing the other error `Region .... does not align` anymore though.

**Comment by jbusecke** [comment]
Same thing if I provide only the lon, lat, time values for static chunks.

**Comment by jbusecke** [comment]
`decode_coords=all` does not help either.

**Comment by jbusecke** [comment]
So I am running out of ideas right now. 

One thing I was wondering though. Is this an issue with one dimension not being a coordinate (`bnds`): 
image

**Comment by jbusecke** [comment]
I have the feeling I mentioned something similar to @cisaacstern before somewhere, but cannot remember where...maybe a walk in the beautiful rain in Hamburg will spur my memory.

**Comment by jbusecke** [comment]
To see if this could be the reason for the failure I am now looking for a dataset that has coordinates for bounds, and will run that through the recipe.

**Comment by jbusecke** [comment]
Could not find another iid which has the bounds as coordinate variables, but am trying with another iid now, just to see if the failure is just relevant to a single dataset.

**Comment by jbusecke** [comment]
Def was not unique to that dataset, but I now found one (from [here](https://github.com/pangeo-forge/pangeo-forge-recipes/issues/504#issuecomment-1480988927)) that actually has coordinate values for bounds.

**Comment by jbusecke** [comment]
Oh wow, this just worked! 
```python
import xarray as xr
path = 'gs://leap-persistent-ro/data-library/cmip6-testing/cmip6-template-618127503-5753673214-1/CMIP6.CMIP.NOAA-GFDL.GFDL-CM4.historical.r1i1p1f1.Amon.tas.gr1.v20180701.zarr'
ds = xr.open_dataset(path, engine='zarr', chunks={})
ds
```
image

Checking this now with some more changes in the options...

**Comment by jbusecke** [comment]
Hmmm when I change the aspect ratio i see failures like this: 
```
 line 48, in _store_data raise ValueError( ValueError: Region (slice(0, 1, None), slice(0, 990, None), slice(None, None, None), slice(None, None, None)) does not align with Zarr chunks (990, 180, 288). [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|KeepOnlyVariableId|StoreToZarr/StoreToZarr/StoreDatasetFragments/Map(store_dataset_fragment)-ptransform-32'] Worker ID: cmip6-template-618127503--08031046-3zjq-harness-h1h3
```

I am wondering if the dynamic chunking is failing silently? I am not seeing any of the [print statements](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/8df16bad5acb6973fb227780db980ac1b06c0268/pangeo_forge_recipes/transforms.py#L451) that might give me a clue here. Any way I could inspect these on dataflow @cisaacstern?

**Comment by cisaacstern** [comment]
Awesome progress, @jbusecke. Lmk if there's something specific I can do to help. A few responses below.

> I am not seeing any of the [print statements](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/8df16bad5acb6973fb227780db980ac1b06c0268/pangeo_forge_recipes/transforms.py#L451) that might give me a clue here.

Changing these to `logger.info` calls should surface them into the dataflow logs. See https://github.com/pangeo-forge/pangeo-forge-recipes/pull/548/files for an example.

> Does the rechunking/combining fail on datasets with a non-coordinate dim? @cisaacstern I think we should investigate this more systematically on the pgf-recipes side?

If you can create an MRE or test for this on `pangeo-forge-recipes` that would be awesome. Happy to take a look at it over there. Probably unrelated but here's an old issue related to dimensions without coordinates: https://github.com/pangeo-forge/pangeo-forge-recipes/issues/214

**Comment by jbusecke** [comment]
> If you can create an MRE or test for this on pangeo-forge-recipes that would be awesome. Happy to take a look at it over there. Probably unrelated but here's an old issue related to dimensions without coordinates: https://github.com/pangeo-forge/pangeo-forge-recipes/issues/214


I think I was starting down that road [here](https://github.com/rabernat/pangeo-forge-recipes/pull/3/files) but that turned out to add a lot of complexity to the end-to-end tests. Ill look into that further and try to come up with a MRE.

FYI, I have the suspicion that this might actually not be unrelated!

**Comment by jbusecke** [comment]
Ok I have a preliminary conclusion here: 

I was able to reproduce the failure above for both iids used when I set the `target_chunks={..., 'bnds':1}` (tested with multiple values for the other dims). If I set `target_chunks={..., 'bnds':2}` I have so far not observed a single failure. I have traced back most failures with the dynamic chunking to this pattern too, and thus conclude this is not an issue with the dynamic chunking, but instead reveals some issues further upstream. My hint from above about the dimension having coordinates/no coordinates seemed to have been a wrong lead too. There is something is still going wrong with the rechunking if the dataset has dimensions on coordinates which are not present on the data_variable.

The good news here is that the dynamic chunking works pretty well, and once the upstream bug is fixed should work as intended here. 

I think I can split these issues up into several different parallel tasks:
- [ ] Make a MRE for this bug and submit an issue about this.
- [ ] Reduce the scope of this PR for now, go back to only chunking in time (and leaving all other dims unchunked) for now.

**Comment by jbusecke** [comment]
@cisaacstern I think the most feasible way to package these iids in batches would be to have dictionary object like we did [here](https://github.com/pangeo-forge/cmip6-feedstock/blob/main/feedstock/recipe.py) a while back. 
I naively tried to implement this with two iids above, but the submission [failed](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/5777714649/job/15658189155). I am not sure if this workflow is even compatible with the deploy action? Ideally I want to submit one dataflow job per dict key-value pair.

**Comment by jbusecke** [comment]
Hmm I might have spoken too soon. [These changes]([modify aspect ratio](https://github.com/leap-stc/cmip6-leap-feedstock/pull/4/commits/cffa620bc5008f494dce4893cbffa8701b0a841f)) still reproduce something similar to [above](https://github.com/leap-stc/cmip6-leap-feedstock/pull/4#issuecomment-1663137723). It must be more complex than just whether to chunk the bounds or not. I wonder if it has to do with the fact if the spatial coordinates are chunked or not. Trying now with pure time chunking alone....

**Comment by jbusecke** [comment]
I now have two recipes running with the deployment action and will merge this, since I think the purpose of a baseline example has been achieved. I will work in seperate PRs to scale this effort up to a first request batch (probably keeping dynamic chunking in time only), and resolving the upstream issues with certain chunking inputs on the PGF-recipe side.

**Pull request merged**
