### PR TITLE
Test fix for multidim rechunking _invert_meshgrid error

### PR DESCRIPTION
**Pull request by jbusecke**
@cisaacstern and I just came up with a fix for https://github.com/pangeo-forge/pangeo-forge-recipes/pull/658 and I want to see if this alleviates some of the failures I have seen.

- [x] Revert test pr iid list changes once they ran.

### CODE REVIEW

**Comment by jbusecke** [comment]
@rsignell I just added the iids from #73 to the PR test list to see if this fixes the issue. Stay tuned.

**Comment by jbusecke** [comment]
Trying to submit some runs from the `MPI-ESM1-2-LR`, which previously [failed](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-02-05_14_32_00-11974078276744862167;step=Creating%20CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r49i1p1f1.Omon.chl.gn.v20190815%7COpenURLWithFSSpec%7COpenWithXarray%7CPreprocessor%7CStoreToZarr%7CCopy%7CLogging%20to%20bigquery%20%28non-QC%29%7CTestDataset%7CLogging%20to%20bigquery%20%28QC%29;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=leap-pangeo) due to this particular error.

**Comment by jbusecke** [comment]
So far all the MPI runs pass now 🚀 [Example](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-02-09_16_26_35-7634262405417644621?project=leap-pangeo)

Waiting for the HighResMIP runs now.

**Comment by jbusecke** [comment]
HELL YEAH, [one of them ran successful](https://console.cloud.google.com/dataflow/jobs/us-central1/2024-02-09_16_15_39-237853338270888151;step=Creating%20CMIP6.HighResMIP.MOHC.HadGEM3-GC31-HH.highres-future.r1i1p1f1.Omon.thetao.gn.v20200514%7COpenURLWithFSSpec%7COpenWithXarray%7CPreprocessor%7CStoreToZarr%7CCopy%7CLogging%20to%20bigquery%20%28non-QC%29%7CTestDataset%7CLogging%20to%20bigquery%20%28QC%29;graphView=0?project=leap-pangeo&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22))) already.

**Comment by jbusecke** [comment]
There is is @rsignell: 
image

Nicely chunked in space. Ill consider this a success and merge this to the main branch.

**Comment by rsignell** [comment]
That is awesome Julius! Way to go!!

**Comment by jbusecke** [comment]
The other runs were killed by our zombie killer. I will adjust the timing of that for now, merge this and see how the full time range datasets fare.

**Comment by rsignell** [comment]
This is exciting!!

**Pull request merged**
