### PR TITLE
Debug recent recipe failure

### PR DESCRIPTION
**Pull request by jbusecke**

### CODE REVIEW

**Comment by jbusecke** [comment]
It seems like I am still getting the [same error](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/6085623589/job/16510156470#step:5:236) @cisaacstern. I did merge main into my [-runner dev branch](https://github.com/jbusecke/pangeo-forge-runner/tree/dev), so I am assuming I am getting the fixes you merged. Not sure if there is something else that needs fixing, or if the additional changes in there mess something up. 

But the `unsupported operand type(s) for /: 'RequiredAtRuntimeDefault' and 'str'` still makes me think that there is a bug in the injection logic.

**Comment by jbusecke** [comment]
Ok so removing the resource hint from `StoreToZarr` made the submission succeed, but I am getting weird errors in the preprocessor stage: 
```
in _keep_only_variable_id AttributeError: 'OpenFile' object has no attribute 'data_vars' [while running 'Creating CMIP6.CMIP.CSIRO-ARCCSS.ACCESS-CM2.historical.r3i1p1f1.SImon.sifb.gn.v20200817|OpenURLWithFSSpec|Preprocessor|OpenWithXarray|StoreToZarr|Logging to non-QC table|TestDataset|Logging to QC table/Preprocessor/Fix coordinates
```

I interpret [this](https://github.com/leap-stc/cmip6-leap-feedstock/blob/6b1c72714abb4d930ac20323682ca56700b4eb8c/feedstock/recipe.py#L175) (and similar) lines as the root cause. I was under the assumption that the pcollection returns tuples of `(indicies, xr.Datasets)`, is that not correct anymore? 

@cisaacstern sorry to bother you again, I guess this is what I get for rebasing everything...

**Comment by jbusecke** [comment]
Oh wait, is this the same issue as above, but with the caching injection? Ill remove all the resource hints, and test this.

**Comment by jbusecke** [comment]
Hmmm that did not do the trick. Now I am getting a bunch of 
```
AttributeError: 'GCSFile' object has no attribute 'data_vars' [while running 'Creating CMIP6.CMIP.MPI-M.MPI-ESM1-2-LR.historical.r19i1p1f1.SImon.sifb.gn.v20210901|OpenURLWithFSSpec|Preprocessor|OpenWithXarray|StoreToZarr|Logging to non-QC table|TestDataset|Logging to QC table/Preprocessor/Fix coordinates-ptransform-87']
"
```

very strange...

**Comment by jbusecke** [comment]
Oh my, how did the preprocessor stage slip before the open with xarray stage? And why did that work before? so many questions, but the good thing is, this is fixed now, and the errors raised were helpful. Also thanks @cisaacstern for helping this slightly tired dummy over here...

**Comment by cisaacstern** [comment]
The only thing I object to in your comment is the self-deprecation. Onward 🚀 😄

**Comment by jbusecke** [comment]
This seems to work decently again. Will merge to add more iids in a fresh PR

**Pull request merged**
